name: Copy code to S3

on:
  push:
    branches: [ main ]
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: write    # This is required for actions/checkout
jobs:
  build-and-deploy:
    runs-on: [ ubuntu-latest ]
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: List Files after
        run: ls -a
      - name: show credentials
        run: echo ${{ vars.AWS_ROLE }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: 'us-east-1'
      - name: copy to S3
        run: aws s3 sync ./. s3://github-code-repo/copy_repo_s3/
