name: Copy code to S3

on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: List Files Before
        run: ls -a
      - uses: actions/checkout@v3
      - name: List Files After
        run: ls -a
